/*
#389 Easy
Given two strings s and t which consist of only lowercase letters.  String t is generated by random shuffling string s and then add one more letter at a random position.  
Find the letter that was added in t.
*/

class Solution {
    public char findTheDifference(String s, String t) {
        
        char[] sArr = s.toCharArray();
        char[] tArr = t.toCharArray();
        
        Arrays.sort(sArr);
        Arrays.sort(tArr);
        
        for (int i = 0; i < sArr.length; i++) {
            if (tArr[i] != sArr[i])
                return tArr[i];
        }
        
        return tArr[tArr.length-1];
    }
}
